config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :resources
  resources :categories
  resources :requests do
    member do
      get :assign_technician_form
      patch :assign_technician
      patch :attend
    end
  end

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id             :bigint           not null, primary key
#  description    :text
#  priority       :string
#  status         :string
#  title          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  assigned_to_id :bigint
#  resource_id    :bigint           not null
#  user_id        :bigint           not null
#
# Indexes
#
#  index_requests_on_assigned_to_id  (assigned_to_id)
#  index_requests_on_resource_id     (resource_id)
#  index_requests_on_user_id         (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (assigned_to_id => users.id)
#  fk_rails_...  (resource_id => resources.id)
#  fk_rails_...  (user_id => users.id)
#
class Request < ApplicationRecord
  include Observable

  belongs_to :resource
  belongs_to :user
  belongs_to :assigned_to, class_name: 'User', optional: true

  validates :resource, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :priority, presence: true
  validates :status, presence: true

  enum priority: { low: 'low', medium: 'medium', high: 'high' }
  enum status: { open: 'open', accepted: 'accepted', rejected: 'rejected', closed: 'closed' }

  before_validation :set_default_status
  validate :resource_must_be_available, on: :create

  def attend
    self.status = 'closed'
  end

  private

  def set_default_status
    self.status ||= 'open'
  end

  def resource_must_be_available
    errors.add(:resource, "não está disponível") unless resource&.available?
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  load_and_authorize_resource
  before_action :set_request, only: %i[ show edit update destroy ]
  before_action :authorize_supervisor, only: [:assign_technician, :assign_technician_form]
  before_action :authorize_technician, only: [:attend]

  def index
    @requests = Request.all
  end

  def show
  end

  def new
    @request = Request.new
  end

  def edit
  end

  def create
    @request = Request.new(request_params)
    @request.user = current_user
    @request.status = 'open'

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: "Solicitação criado." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: "Solicitação atualizada." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @request.destroy!

    respond_to do |format|
      format.html { redirect_to requests_path, status: :see_other, notice: "Solicitação apagada." }
      format.json { head :no_content }
    end
  end

  def assign_technician
    @request = Request.find(params[:id])
    @request.add_observer(NotificationObserver.new(@request.user))
    @technician = User.find(request_params[:assigned_to_id])

    respond_to do |format|
      if @request.update(assigned_to: @technician, status: 'accepted')
        format.html { redirect_to @request, notice: "Técnico atribuído com sucesso." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { redirect_to @request, alert: "Falha ao atribuir técnico." }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def assign_technician_form
    @request = Request.find(params[:id])
  end

  def attend
    @request = Request.find(params[:id])
    @request.add_observer(NotificationObserver.new(@request.user))

    respond_to do |format|
      if @request.attend && @request.save
        format.html { redirect_to @request, notice: "Solicitação atendida com sucesso." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { redirect_to @request, alert: "Falha ao atender solicitação." }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_request
      @request = Request.find(params[:id])
    end

    def request_params
      params.require(:request).permit(:title, :description, :status, :priority, :resource_id, :user_id, :assigned_to_id)
    end

    def authorize_supervisor
      unless current_user.supervisor?
        redirect_to requests_path, alert: "Apenas supervisores podem atribuir técnicos."
      end
    end

    def authorize_technician
      unless current_user.technician? && @request.accepted?
        redirect_to requests_path, alert: "Apenas técnicos podem atender solicitações aceitas."
      end
    end
end

app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, "Título", style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, "Descrição", style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :priority, "Prioridade", style: "display: block" %>
    <%= form.select :priority, Request.priorities.keys.map { |priority| [I18n.t("activerecord.enums.request.priority.#{priority}"), priority] }, prompt: "Selecione a prioridade" %>
  </div>

  <div>
    <%= form.label :resource_id, "Recurso", style: "display: block" %>
    <%= form.collection_select :resource_id, Resource.all, :id, :name, prompt: "Selecione um recurso" %>
  </div>

  <div>
    <%= form.submit "Salvar solicitação" %>
  </div>
<% end %>

app/views/requests/_request.html.erb
<div id="<%= dom_id request %>">
  <p>
    <strong>Titulo:</strong>
    <%= request.title %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= request.description %>
  </p>

  <p>
    <strong>Prioridade:</strong>
    <%= I18n.t("activerecord.enums.request.priority.#{request.priority}") %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= I18n.t("activerecord.enums.request.status.#{request.status}") %>
  </p>

  <p>
    <strong>Técnico Responsável:</strong>
    <%= request.assigned_to&.name %>
  </p>

  <p>
    <strong>Solicitante:</strong>
    <%= request.user.name %>
  </p>

  <p>
    <strong>Recurso:</strong>
    <%= request.resource.name %>
  </p>
</div>

app/views/requests/assign_technician_form.html.erb
<h1>Atribuir Técnico</h1>

<%= form_with(model: @request, url: assign_technician_request_path(@request), local: true, method: :patch) do |form| %>
  <div class="field">
    <%= form.label :assigned_to_id, "Selecionar Técnico" %>
    <%= form.collection_select :assigned_to_id, User.technician, :id, :name, prompt: "Escolha um técnico" %>
  </div>

  <div class="actions">
    <%= form.submit "Atribuir Técnico" %>
  </div>
<% end %>

<%= link_to 'Voltar', request_path(@request) %>

app/views/requests/edit.html.erb
<h1>Editando solicitação</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Exibir solicitação", @request %> |
  <%= link_to "Voltar para solicitações", requests_path %>
</div>

app/views/requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Solicitações</h1>

<div id="requests">
  <% @requests.each do |request| %>
    <% if current_user.technician? && request.accepted? %>
      <%= render request %>
      <p>
        <%= link_to "Ver solicitação", request %>
      </p>
    <% elsif !current_user.technician? %>
      <%= render request %>
      <p>
        <%= link_to "Ver solicitação", request %>
      </p>
    <% end %>
  <% end %>
</div>

<%= link_to "Nova solicitação", new_request_path %>

app/views/requests/new.html.erb
<h1>Nova solicitação</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Voltar para solicitações", requests_path %>
</div>

app/views/requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @request %>

<div>
  <% if current_user.supervisor? %>
    <%= link_to "Atribuir técnico", assign_technician_form_request_path %> |
  <% end %>
  <%= link_to "Editar essa solicitação", edit_request_path(@request) %> |
  <%= link_to "Voltar para solicitações", requests_path %>

  <%= button_to "Deletar solicitação", @request, method: :delete %>

  <% if current_user.technician? && @request.accepted? %>
    <%= button_to "Atender solicitação", attend_request_path(@request), method: :patch %>
  <% end %>
</div>