config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :resources
  resources :categories
  resources :requests do
    member do
      get :assign_technician_form
      patch :assign_technician
      patch :attend
    end
  end

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/resources/_form.html.erb
<%= form_with(model: resource) do |form| %>
  <% if resource.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Nome, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :Tipo, style: "display: block" %>
    <%= form.text_field :resource_type %>
  </div>

  <div>
    <%= form.label :Quantidade, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :Disponível, style: "display: block" %>
    <%= form.check_box :availability %>
  </div>

  <div>
    <%= form.label :Categoria, style: "display: block" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "Selecione uma categoria" %>
  </div>

  <div>
    <%= form.submit "Salvar recurso" %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div id="<%= dom_id resource %>">
  <p>
    <strong>Nome:</strong>
    <%= resource.name %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= resource.resource_type %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= resource.amount %>
  </p>

  <p>
    <strong>Disponibilidade:</strong>
    <%= resource.availability %>
  </p>

  <p>
    <strong>Categoria:</strong>
    <%= resource.category&.name %>
  </p>

</div>

app/views/resources/edit.html.erb
<h1>Editando recurso</h1>

<%= render "form", resource: @resource %>

<br>

<div>
  <%= link_to "Exibir recurso", @resource %> |
  <%= link_to "Voltar para recursos", resources_path %>
</div>

app/views/resources/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recursos</h1>

<div id="resources">
  <% @resources.each do |resource| %>
    <%= render resource %>
    <p>
      <%= link_to "Ver recurso", resource %>
    </p>
  <% end %>
</div>

<%= link_to "Novo recurso", new_resource_path %>

app/views/resources/new.html.erb
<h1>Novo recurso</h1>

<%= render "form", resource: @resource %>

<br>

<div>
  <%= link_to "Voltar para recursos", resources_path %>
</div>

app/views/resources/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @resource %>

<div>
  <%= link_to "Editar esse recurso", edit_resource_path(@resource) %> |
  <%= link_to "Voltar para recursos", resources_path %>

  <%= button_to "Deletar recurso", @resource, method: :delete %>
</div>