config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :resources
  resources :categories
  resources :requests do
    member do
      get :assign_technician_form
      patch :assign_technician
      patch :attend
    end
  end

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to "PDS Project", root_path %>
      <nav>
        <ul>
          <li><%= link_to "Página principal", root_path %></li>
          <% if can? :read, Resource %>
            <li><%= link_to "Recursos", resources_path %></li>
          <% end %>
          <% if can? :read, Category %>
            <li><%= link_to "Categorias", categories_path %></li>
          <% end %>
          <% if can? :read, Request %>
            <li><%= link_to "Solicitações", requests_path %></li>
          <% end %>
          <% if user_signed_in? %>
            <li><%= link_to "Sair", destroy_user_session_path , method: :delete %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message) %>
    <% end %>
    <%= yield %>
  </body>
  </html>